### ISSUE TITLE
Build a MonkeyC plugin for a decent IDE

### ISSUE THREAD

**Issue by snobu** [garmin/connectiq-apps#14]
Dear Garmin,

Please build a MonkeyC plugin for a decent IDE, Visual Studio Code, Atom, whatever you feel like targeting, just please **please** let me build apps with humanity and decency, don't make me use Eclipse.

I thank you.

**Comment by AlphaMonkeyConnectIQ** [comment]
I think this is what you are looking for: https://github.com/genecyber/connectiq-build

**Comment by snobu** [comment]
No. I'm looking for a coherent, official effort from Garmin to support a modern IDE.

**Comment by julie-bsx** [comment]
And now I feel really bad that I think Eclipse is awesome.

Okay, I don't really feel bad.

**Comment by xehpuk** [comment]
Any updates on this?

**Comment by flowstatedev** [comment]
My two cents:
- Eclipse is fine, if a little bloated and maybe lacking in certain areas
- With all due respect, there are already so many issues with the Eclipse plug-in (and other areas of CIQ) that I would prefer that Garmin doesn't spread its resources even thinner. To be fair, lots of bugs have been fixed in the past two years, and I'm sure we all appreciate that. 

But I really think I'd like to see a **feature-complete**, bug-free version of the Eclipse plugin before Garmin decides to support any other IDEs.

**Comment by snobu** [comment]
I guess you're right. Could be worse. Could be Xcode. Owners should feel free to close this if it's not of interest, no hard feelings :)

**Comment by flowstatedev** [comment]
Haha. Sorry I didn't mean to sound harsh. I do get where you're coming from, and fwiw, I would leave the issue open. (I thought about it and changed my vote....)

**Comment by kyxap** [comment]
my Vote for IntelliJ

**Comment by flowerett** [comment]
Here's the [VSCode plugin](https://marketplace.visualstudio.com/items?itemName=garmin.monkey-c)
It was first released on 13/10/2020 and updated a few times after that.

**Comment by snobu** [comment]
Thank you for this. It's never too late to improve developer experience. Cheers!
